import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { alignItems: 'center' },
  QuestionContainer: {
    width: 300,
    height: 60,
    top: 20,
    borderRadius: 10,
    alignSelf: 'center',
    justifyContent: 'center',
    position: 'absolute',
    color: '#000000',
    backgroundColor: '#FFFFFF',
    shadowColor: '#171717',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
  },
  QuestionText: {
    fontFamily: 'PoppinsSemiBold',
    fontSize: 14,
    paddingHorizontal: 10,
    textAlign: 'center',
  },
  displayContainer: {
    width: 300,
    height: 100,
    top: 90,
    borderRadius: 10,
    alignSelf: 'center',
    justifyContent: 'center',
    position: 'absolute',
    color: '#000000',
    backgroundColor: '#FFFFFF',
    shadowColor: '#171717',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
  },
  displayText: {
    fontFamily: 'PoppinsSemiBold',
    color: '#000',
    textAlign: 'center',
    fontSize: 18,
  },
  input: {
    width: 300,
    height: 50,
    borderColor: '#3F51B5',
    borderWidth: 2,
    borderRadius: 5,
    top: 320,
    paddingLeft: 10,
    fontFamily: 'PoppinsMedium',
  },
  sumbitBtn: {
    backgroundColor: '#3F51B5',
    alignSelf: 'center',
    position: 'absolute',
    top: 400,
    height: 50,
    borderRadius: 10,
    width: 160,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 5,
    borderBottomColor: '#2C3A87',
  },
  btnText: {
    color: '#ffffff',
    fontSize: 18,
    fontFamily: 'PoppinsSemiBold',
  },
  correctcontainer: {
    alignItems: 'center',
    top: 350,
  },
  feedback: {
    position: 'absolute',
    fontWeight: 'medium',
    fontFamily: 'PoppinsSemiBold',
    color: '#3F51B5',
    paddingHorizontal: 20,
    fontSize: 22,
    textAlign: 'center',
  },
  summarycontainer: {
    backgroundColor: '#C0C0C0',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: 100,
    height: 100,
    width: 300,
    backgroundColor: '#FFFFFF',
    color: '#000000',
    shadowColor: '#171717',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5, // Android
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  summarytext: {
    fontSize: 12,
    fontFamily: 'PoppinsMedium',
  },
});
