import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  containerTo: {
    flex: 1,
  },
  container: {
    marginTop: 320,
    height: 500,
  },
  btnView: {
    position: 'absolute',
    width: '80%',
    top: '14%',
    alignSelf: 'center',
  },
  letsplay: {
    position: 'absolute',
    left: '10%',
    top: '12%',
    width: '80%',
    height: 42,
    fontSize: 32,
    fontFamily: 'PoppinsBold',
    color: '#000000',
  },
  recommendedtext: {
    position: 'absolute',
    fontFamily: 'PoppinsSemiBold',
    left: '10%',
    top: '25%',
    height: 42,
    fontSize: 16,
    color: '#000000',
  },
  recommendedview: {
    top: '30%',
    left: '8%',
    position: 'absolute',
    height: 95,
    marginRight: 40,
  },
  allquizzes: {
    position: 'absolute',
    fontFamily: 'PoppinsSemiBold',
    left: '10%',
    top: '45%',
    height: 42,
    fontSize: 16,
    color: '#000000',
  },
  imgButton: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
    height: '100%',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  imgBtn_profile: {
    left: '90%',
    bottom: '30%',
    width: 40,
    height: 40,
    borderRadius: 22,
  },
  refreshBtn: {
    width: 20,
    height: 20,
    position: 'absolute',
    right: '10%',
    top: '45%',
  },
  infoicon: {
    position: 'absolute',
    right: '11%',
    top: '25%',
  },
  loginBtn: {
    backgroundColor: '#2e216f',
    alignSelf: 'center',
    position: 'relative',
    height: 40,
    borderRadius: 10,
    width: 250,
    margin: 10,
  },
  resultBtn: {
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#3F51B5',
    borderRadius: 22,
    width: 314,
    height: 60,
    marginBottom: 50,
  },
  resultTxt: {
    color: 'white',
    alignSelf: 'center',
    fontSize: 25,
    fontWeight: 'bold',
  },
  recommendedquiz: {
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: '#3F51B5',
    position: 'absolute',
    borderRadius: 10,
    top: '30%',
    left: '12%',
    width: 124,
    height: 77,
  },
});
