import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  containerTo: {
    flex: 1,
  },
  textWrapper: {
    textAlign: 'center',
    marginLeft: 40,
    marginRight: 40,
    bottom: 60,
  },
  Infotext: {
    color: '#000',
    fontSize: 30,
    fontWeight: 'bold',
  },
  levelText: {
    fontSize: 16,
    color: '#000',
    top: 440,
    fontWeight: '500',
    position: 'absolute',
  },
  descriptionText: {
    fontSize: 15,
    fontWeight: '600',
    marginTop: 10,
  },
  startBtn: {
    backgroundColor: '#3F51B5',
    alignSelf: 'center',
    position: 'absolute',
    top: 620,
    height: 78,
    borderRadius: 22,
    width: 314,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'grey',
    shadowOffset: { width: 1, height: 5 },
    shadowOpacity: 30,
    shadowRadius: 3,
  },
  btnText: {
    color: '#ffffff',
    fontSize: 27,
    fontFamily: 'PoppinsBold',
  },
  leaderboard: {
    top: 120,
    width: 300,
    height: 260,
    borderRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#171717',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  leaderboardtitle: {
    fontFamily: 'PoppinsBold',
    fontSize: 22,
    right: 80,
    bottom: 2,
  },
  leaderboardentry: {
    width: 260,
    height: 50,
    marginTop: 10,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#3F51B5',
    justifyContent: 'space-around',
    shadowColor: '#171717',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  leaderboardtext: {
    fontFamily: 'PoppinsSemiBold',
    color: '#FFFFFF',
    fontSize: 14,
  },
});
