import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  title: {
    position: 'absolute',
    alignSelf: 'center',
    top: '15%',
    width: '80%',
    height: 40,
    fontSize: 23,
    fontWeight: 'bold',
    color: '#000000',
  },
  sidebyside: {
    alignSelf: "center",
    flexDirection: 'row',
    width: '90%',
    top: "60%",
    justifyContent: 'center',
  },
  buttonManageQuizPage: {
    flexDirection: 'row',
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    elevation: 8,
    width: '45%',
    height: 80,
    alignSelf: "flex-end",
    marginLeft: 10,
    alignItems: 'center',
  },
  YourAccountText1: {
    color: 'white',
    fontFamily: 'PoppinsSemiBold',
    width: '72%',
    fontSize: 18,
    marginLeft: 15,
    alignSelf: "center",
    textAlignVertical: "center",
    textAlign:"center",
  },
  buttonManageUserPage: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 80,
    width: '45%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginRight: 10,
  },
  appButtonContainer2: {
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 22,
    height: 80,
    width: '85%',
    alignSelf: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 30,
    marginRight: 10,
  },
  buttonProgressPage: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 80,
    width: '45%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginLeft: 10,
  },
  buttonResultsPage: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 80,
    width: '45%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginRight: 10,
  },
  buttonDashboardPage: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 80,
    width: '45%',
    alignSelf: "flex-start",
    marginRight: 10,
    alignItems: 'center',
  },
  buttonChangePasswordPage: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 80,
    width: '45%',
    alignSelf: "flex-start",
    marginLeft: 10,
    marginTop: 20,
    alignItems: 'center',
  },

  normalButtonProgressPage: {
    flexDirection: 'row',
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    paddingVertical: 10,
    marginTop: "60%",
    width: '85%',
    height: 60, 
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  normalButtonResultsPage: {
    flexDirection: 'row',
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    paddingVertical: 10,
    marginTop: 20,
    width: '85%',
    height: 60, 
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  normalButtonChangePasswordPage: {
    flexDirection: 'row',
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    paddingVertical: 10,
    marginTop: 20,
    width: '85%',
    height: 60, 
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },

  YourAccountText2: {
    color: 'white',
    fontWeight: 'bold',
    alignSelf: 'center',
    fontSize: 25,
  },

  btnBackToHome: {
    width: 50,
    height: 50,
    borderRadius: 10,
    position: 'absolute',
    left: '80%',
    top: '13.5%',
    fontSize: 20,
  },

  knapptext: {
    fontSize: 32,
    alignSelf: 'center',
    color: 'black',
    padding: 5,
    paddingLeft: 10,
    fontWeight: 'bold',
  },
  icons: { right: 85 },
});
