import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  title: {
    position: 'absolute',
    alignSelf: 'center',
    top: '15%',
    width: '80%',
    height: 40,
    fontSize: 23,
    fontWeight: 'bold',
    color: '#000000',
  },

  appButtonContainer1: {
    flexDirection: 'row',
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    paddingVertical: 10,
    marginTop: 200,
    width: '80%',
    height: 60,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  YourAccountText1: {
    color: 'white',
    fontFamily: 'PoppinsSemiBold',
    alignSelf: 'center',
    fontSize: 20,
  },
  appButtonContainer3: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 60,
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  appButtonContainer2: {
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 22,
    height: 60,
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 30,
  },
  appButtonContainer4: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 60,
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  appButtonContainer5: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 60,
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  appButtonContainer6: {
    flexDirection: 'row',
    elevation: 8,
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    height: 60,
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    top: 180,
  },

  YourAccountText2: {
    color: 'white',
    fontWeight: 'bold',
    alignSelf: 'center',
    fontSize: 25,
  },

  btnBackToHome: {
    width: 50,
    height: 50,
    borderRadius: 10,
    position: 'absolute',
    left: '80%',
    top: '13.5%',
    fontSize: 20,
  },

  knapptext: {
    fontSize: 32,
    alignSelf: 'center',
    color: 'black',
    padding: 5,
    paddingLeft: 10,
    fontWeight: 'bold',
  },
  icons: { right: 85 },
});
